[project]
name = "formattex-pre-commit"
version = "0.1.0"
dependencies = [
    "formattex==0.1.4",
    "formatbibtex==0.0.2",
]

[project.optional-dependencies]
dev = [
    "tomli",
    "tomli_w",
    "urllib3",
    "packaging"
]
